# Generated by Django 4.1.5 on 2023-01-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="imdb",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
