# Generated by Django 4.1.5 on 2023-01-06 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_ticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="seats",
        ),
        migrations.CreateModel(
            name="TicketTypeQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.ticket"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="ticket_type_quantities",
            field=models.ManyToManyField(to="home.tickettypequantity"),
        ),
    ]
